# Cryptostore sample config file for Docker

cache: redis

redis:
    ip: redisdb
    port: 6379
    del_after_read: true
    start_flush: true
    socket: null

exchanges:
    BITMEX:
        l2_book:
            symbols: [XBTUSD, XBTZ20, XBTH21, XBTM21]
            max_depth: 10
        trades: [XBTUSD, XBTZ20, XBTH21, XBTM21]
        ticker: [XBTUSD, XBTZ20, XBTH21, XBTM21]
        funding: [XBTUSD, XBTZ20, XBTH21, XBTM21]
    COINBASE:
        l3_book:
            symbols: [BTC-USD]
            book_delta: true
            book_interval: 10000
        trades: [BTC-USD]

storage: [arctic]
arctic: mongodb://mongo:27017

storage_interval: 60
storage_retries: 5
storage_retry_wait: 30

plugins:
  backfill:
    module: [cryptostore.plugin.backfill, Backfill]
    config: config.yaml

backfill:
    COINBASE:
        BTC-USD:
            start: '2017-01-01'
